on:
  push:
    branches:
      - master

name: Docker Build

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container image
        run: docker build -t stewart:${GITHUB_SHA::8} .
